### ISSUE TITLE
`2.6.2` does not contain `lib/coverage/coverage-level`

### ISSUE THREAD

**Issue by selaux** [gemini-testing/gemini-core#24]
After yesterdays package update to `2.6.2`, I get when running gemini:

```
Error: Cannot find module './lib/coverage/coverage-level'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/nix/store/szgph11cai3sf5w52b3hv3hkc2kqfsjl-mhc-node-modules/node_modules/gemini-core/index.js:20:24)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/nix/store/szgph11cai3sf5w52b3hv3hkc2kqfsjl-mhc-node-modules/node_modules/gemini/lib/passthrough-emitter.js:4:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

Looking into my `node_modules` folder this file does indeed not exist. It is also not included when downloading the `tgz` directly from npm. Can you publish a new version that includes the file?

**Comment by sipayRT** [comment]
hi
but it already exists (here screen of the installed gemini-core@2.6.2):

<img width="776" alt="1 sipayrt 5 sites tmp node_modules gemini-core lib zsh -2018-02-27_13-38-00" src="https://user-images.githubusercontent.com/1658415/36724255-b20a017e-1bc3-11e8-93cd-f941e5e2d584.png">

**Comment by selaux** [comment]
Hm, I don't know what i looked at this morning. Because now I see that it exists... I am now confused and will have another look...

**Comment by selaux** [comment]
Allright, I identified the issue, it was clearly on our side. Sorry for interrupting...
